name: Apollo Schema Check Action
description: A GitHub Action to run a schema check and post the results as a comment on a Pull Request
author: Ian Sutherland

inputs:
  config:
    description: Path to your Apollo config file
    required: false
  graph:
    description: The ID of the graph in Apollo Graph Manager to check your proposed schema changes against. Overrides config file if set.
    required: false
  variant:
    description: The variant to check the proposed schema against
    required: false
  endpoint:
    description: The URL for the CLI to use to introspect your service
    required: false
  headers:
    description: 'Additional headers to send to server for introspectionQuery. Multiple headers can be provided as a comma separated list. NOTE: The `endpoint` input is REQUIRED if using the `headers` input.'
    required: false
  key:
    description: The API key to use for authentication to Apollo Graph Manager
    required: true
  localSchemaFile:
    description: Path to one or more local GraphQL SDL file(s). Supports comma-separated list of paths (ex. `schema.graphql,extensions.graphql`)
    required: false
  queryCountThreshold:
    description: Minimum number of requests within the requested time window for a query to be considered
    required: false
  queryCountThresholdPercentage:
    description: Number of requests within the requested time window for a query to be considered, relative to total request count. Expected values are between 0 and 0.05 (minimum 5% of total request volume)
    required: false
  serviceName:
    description: Provides the name of the implementing service for a federated graph. This flag will indicate that the schema is a partial schema from a federated service
    required: false
  validationPeriod:
    description: 'The size of the time window with which to validate the schema against. You may provide a number (in seconds), or an ISO8601 format duration for more granularity (see: https://en.wikipedia.org/wiki/ISO_8601#Durations)'
    required: true
  title:
    description: The name of the graph which will be shown in the comment
    required: false
  alwaysComment:
    description: Leave a comment on the PR even if there are no schema changes in the PR
    default: 'false'
    required: false
  failOnError:
    description: Fail the check if breaking changes or composition errors are found
    default: 'true'
    required: false

runs:
  using: node16
  main: build/index.js

branding:
  icon: check-square
  color: green
